### ISSUE TITLE
Project is broken out of the box...  

### ISSUE THREAD

**Issue by aturner-tvpage** [scala/scala-seed.g8#22] opened 2018-03-30 21:06 UTC
Output:

ATurner:tvpage aturner$ sbt new sbt/scala-seed.g8

[info] Set current project to tvpage (in build file:/Users/aturner/work/tvpage/)
[info] Set current project to tvpage (in build file:/Users/aturner/work/tvpage/)

A minimal Scala project. 

name [Scala Seed Project]: 

Template applied in ./scala-seed-project

ATurner:tvpage aturner$ cd ./scala-seed-project/
ATurner:scala-seed-project aturner$ sbt test
[info] Loading project definition from /Users/aturner/work/tvpage/scala-seed-project/project
[info] Updating ProjectRef(uri("file:/Users/aturner/work/tvpage/scala-seed-project/project/"), "scala-seed-project-build")...
[info] Done updating.
[info] Compiling 1 Scala source to /Users/aturner/work/tvpage/scala-seed-project/project/target/scala-2.12/sbt-1.0/classes ...
[info] Done compiling.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/Users/aturner/.sbt/boot/scala-2.12.4/org.scala-sbt/sbt/1.1.1/protobuf-java-3.3.1.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[info] Loading settings from build.sbt ...
[info] Set current project to Hello (in build file:/Users/aturner/work/tvpage/scala-seed-project/)
[info] Updating ...
[info] Done updating.
[info] Compiling 1 Scala source to /Users/aturner/work/tvpage/scala-seed-project/target/scala-2.12/classes ...
[info] Done compiling.
[info] Compiling 1 Scala source to /Users/aturner/work/tvpage/scala-seed-project/target/scala-2.12/test-classes ...
[error] /Users/aturner/work/tvpage/scala-seed-project/src/test/scala/example/HelloSpec.scala:6:22: value should is not a member of String
[error]   "The Hello object" should "say hello" in {
[error]                      ^
[error] /Users/aturner/work/tvpage/scala-seed-project/src/test/scala/example/HelloSpec.scala:7:20: value shouldEqual is not a member of String
[error]     Hello.greeting shouldEqual "hello"
[error]                    ^
[error] two errors found
[error] (Test / compileIncremental) Compilation failed
[error] Total time: 4 s, completed Mar 30, 2018, 2:05:07 PM
ATurner:scala-seed-project aturner$

**Comment by SethTisue** [comment] 2018-03-30 21:18
looks like a manifestation of https://github.com/scala/scala-dev/issues/480, which is a regression in Scala 2.12.5 on Java 9 & 10

in the short term, if you are trying to get started with the language, you should find that using Java 8 works fine as a workaround.

but also, I don't understand why this is happening to you, because https://github.com/scala/scala-seed.g8/blob/2.12.x/src/main/g8/build.sbt says 2.12.4, not 2.12.5. because we intentionally haven't merged #22 yet, exactly because of scala/scala-dev#480

if I try to reproduce the problem on my own machine, I can't. it works fine, as seen in this transcript: https://gist.github.com/SethTisue/f727ae33a31e01533a1fd4f6468968f3

anyone have an idea how or why @aturner-tvpage's experience was different?

**Comment by aturner-tvpage** [comment] 2018-03-31 00:46
This is weird.  I created a clean directory, and re-ran, and it worked as advertised.  I had created another project moments before the first time, updating the Scala version to the current release, then relatively quickly, re-ran the sbt new, and it failed.  Is it possible something somewhere was caching?

**Comment by aturner-tvpage** [comment] 2018-03-31 00:49
That does in fact appear to be what is occurring!

I build my project that asks for Scala 2.12.5 and it tried to build (and fails right now because, I was half way through something).
Create a new project, run sbt test and it fails!  How interesting..
ATurner:aws-query aturner$ sbt test
[info] Loading project definition from /Users/aturner/work/tvpage/aws-query/project
[info] Loading settings from build.sbt ...
[info] Set current project to aws-report (in build file:/Users/aturner/work/tvpage/aws-query/)
[info] Compiling 2 Scala sources to /Users/aturner/work/tvpage/aws-query/target/scala-2.12/classes ...
[error] /Users/aturner/work/tvpage/aws-query/src/main/scala/com/tvpage/aws/AmazonWebServiceRequestIterator.scala:3:47: identifier expected but ')' found.
[error] class AmazonWebServiceRequestIterator[T](req: ) {
[error]                                               ^
[error] /Users/aturner/work/tvpage/aws-query/src/main/scala/com/tvpage/aws/AmazonWebServiceRequestIterator.scala:5:2: ')' expected but eof found.
[error] }
[error]  ^
[error] two errors found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 3 s, completed Mar 30, 2018, 5:46:49 PM
ATurner:aws-query aturner$ cd ..
ATurner:tvpage aturner$ sbt new sbt/scala-seed.g8
[info] Set current project to tvpage (in build file:/Users/aturner/work/tvpage/)
[info] Set current project to tvpage (in build file:/Users/aturner/work/tvpage/)

A minimal Scala project. 

name [Scala Seed Project]: crikey

Template applied in ./crikey

ATurner:tvpage aturner$ cd crikey/
ATurner:crikey aturner$ sbt test
[info] Loading project definition from /Users/aturner/work/tvpage/crikey/project
[info] Updating ProjectRef(uri("file:/Users/aturner/work/tvpage/crikey/project/"), "crikey-build")...
[info] Done updating.
[info] Compiling 1 Scala source to /Users/aturner/work/tvpage/crikey/project/target/scala-2.12/sbt-1.0/classes ...
[info] Done compiling.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/Users/aturner/.sbt/boot/scala-2.12.4/org.scala-sbt/sbt/1.1.1/protobuf-java-3.3.1.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[info] Loading settings from build.sbt ...
[info] Set current project to Hello (in build file:/Users/aturner/work/tvpage/crikey/)
[info] Updating ...
[info] Done updating.
[info] Compiling 1 Scala source to /Users/aturner/work/tvpage/crikey/target/scala-2.12/classes ...
[info] Done compiling.
[info] Compiling 1 Scala source to /Users/aturner/work/tvpage/crikey/target/scala-2.12/test-classes ...
[error] /Users/aturner/work/tvpage/crikey/src/test/scala/example/HelloSpec.scala:6:22: value should is not a member of String
[error]   "The Hello object" should "say hello" in {
[error]                      ^
[error] /Users/aturner/work/tvpage/crikey/src/test/scala/example/HelloSpec.scala:7:20: value shouldEqual is not a member of String
[error]     Hello.greeting shouldEqual "hello"
[error]                    ^
[error] two errors found
[error] (Test / compileIncremental) Compilation failed
[error] Total time: 4 s, completed Mar 30, 2018, 5:47:59 PM
ATurner:crikey aturner$

**Comment by SethTisue** [comment] 2018-04-17 21:15
> Is it possible something somewhere was caching?

maybe it just overwrote the directory from last time and you ended up with a mix of stuff?

**Comment by SethTisue** [comment] 2018-04-17 21:15
I'm not sure what your other comment is about, maybe ask on https://users.scala-lang.org

**Closed as completed by SethTisue** 2018-04-17 21:15 UTC
